### PR TITLE
Add Wwise plugin to project

### PR DESCRIPTION
**Pull request by alessandrofama**
If you get any errors on Windows you need to install the MSVC C++-x64/x86-Buildtools. Has a dependency on the debug versions of the Windows run-time libraries.

### CODE REVIEW

**Comment by limkevinkuan** [comment]
I have the latest build tools and still get the [Waapi issue](https://github.com/alessandrofama/wwise-godot-integration/issues/38)
Is there something else I need?
image

**Comment by IoriBranford** [comment]
I have the latest build tools and still get the [Waapi issue](https://github.com/alessandrofama/wwise-godot-integration/issues/38)
Is there something else I need?
image

**Comment by IoriBranford** [comment]
I updated my Visual Studio 2019, I don't know if that fixed the problem but it's gone now.

**Comment by alessandrofama** [comment]
Surprised about the error happening with the build tools installed. Weird one. If Godot doesn't complain it is gone. Waapi is not essential, so I can throw it out if it happens again.

**Comment by IoriBranford** [comment]
I was setting up our project on another dev's machine and found it was necessary to install Windows 10 SDK as well. (for ucrtbased.dll)

**Comment by alessandrofama** [comment]
Awesome, thanks for the info.

**Pull request merged**
